// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.ExamAccount.Infrastructure.Persistence;

#nullable disable

namespace PRN232.ExamAccount.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExamAccountDbContext))]
    [Migration("20260721154446_InitThreeRoleWorkflow")]
    partial class InitThreeRoleWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exam")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PaperCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ExamSessionId", "StudentId")
                        .IsUnique();

                    b.ToTable("ExamCandidates", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("ForbidHardcodedConnectionString")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<string[]>("PlagiarismKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("RequireAppSettings")
                        .HasColumnType("boolean");

                    b.Property<string>("RubricVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SolutionPattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExamPapers", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExamRooms", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamSectionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamPaperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TestFilter")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExamPaperId", "Name")
                        .IsUnique();

                    b.ToTable("ExamSections", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ExamPaperId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExamPaperId");

                    b.HasIndex("RoomId");

                    b.ToTable("ExamSessions", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("GradingItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasTechnicalError")
                        .HasColumnType("boolean");

                    b.Property<string>("RawJsonReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RubricVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId")
                        .IsUnique();

                    b.HasIndex("GradingItemId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("GradingAttempts", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("LecturerId");

                    b.ToTable("GradingBatches", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamCandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradingBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("LatestAttemptNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LatestScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExamCandidateId")
                        .IsUnique();

                    b.HasIndex("GradingBatchId");

                    b.ToTable("GradingItems", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GradingBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GradingItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notifications", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("RefreshTokens", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ReviewRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradingItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GradingItemId");

                    b.ToTable("ReviewRequests", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "exam");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamCandidate", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("Candidates")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232.ExamAccount.Domain.Entities.Student", "Student")
                        .WithMany("ExamCandidates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamSectionDefinition", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.ExamPaper", "ExamPaper")
                        .WithMany("Sections")
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamPaper");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.ExamPaper", "ExamPaper")
                        .WithMany("Sessions")
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN232.ExamAccount.Domain.Entities.ExamRoom", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamPaper");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingAttempt", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.GradingItem", "GradingItem")
                        .WithMany("Attempts")
                        .HasForeignKey("GradingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingItem");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingBatch", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("GradingBatches")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN232.ExamAccount.Domain.Entities.UserAccount", "Lecturer")
                        .WithMany("AssignedBatches")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingItem", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.ExamCandidate", "ExamCandidate")
                        .WithOne("GradingItem")
                        .HasForeignKey("PRN232.ExamAccount.Domain.Entities.GradingItem", "ExamCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN232.ExamAccount.Domain.Entities.GradingBatch", "GradingBatch")
                        .WithMany("Items")
                        .HasForeignKey("GradingBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamCandidate");

                    b.Navigation("GradingBatch");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.NotificationRecord", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.UserAccount", "RecipientUser")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ReviewRequest", b =>
                {
                    b.HasOne("PRN232.ExamAccount.Domain.Entities.GradingItem", "GradingItem")
                        .WithMany("ReviewRequests")
                        .HasForeignKey("GradingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingItem");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamCandidate", b =>
                {
                    b.Navigation("GradingItem");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamPaper", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamRoom", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("GradingBatches");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.GradingItem", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("ReviewRequests");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.Student", b =>
                {
                    b.Navigation("ExamCandidates");
                });

            modelBuilder.Entity("PRN232.ExamAccount.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("AssignedBatches");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
